### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by twesterhout** [mklinik/spl-test-programs#1]
Hi,

I'm following the course and would like to use these test programs. The problem is that I can't :( Your repo does not specify a license and according to Github policies, this means that all the code here is copyrighted to you (at least as far as I understand).

Any chance you could add some permissive license (e.g. MIT) so that we all can actually use your code?

Thanks in advance!

Tom

**Comment by mklinik** [comment]
Thanks for the heads up. Licensing my projects is something that I put off way too long.
